### PR TITLE
Fix broken url for ta4j-wiki

### PR DESCRIPTION
**Pull request by HiuKwok**

### CODE REVIEW

**Review by milczarekIT — APPROVED** [review]
Well done!

**Comment by HiuKwok** [comment]
@milczarekIT what action can be done on my side to get this merged?

**Comment by milczarekIT** [comment]
Hi @HiuKwok 
Unfortunately only @team172011 can merge PRs to main branch ;( 
Unfortunately, he does not devote too much time to this repository in last time.
There are at least 3 PRs waiting for merge in ta4ji-wiki and at least 12 PRs waiting for merge in ta4j.

@team172011 - could you merge this PR into master branch? It was reviewed by me.

**Comment by team172011** [comment]
thanks!

**Pull request merged**
