### PR TITLE
Fix a broken link

### PR DESCRIPTION
**Pull request by izeye**
This PR fixes a broken link.

### CODE REVIEW

**Comment by team172011** [comment]
okay, thanks!

**Comment by izeye** [comment]
@team172011 Thanks for the feedback but I don't get what you meant by closing this PR as you didn't merge it nor fix them on your own.

**Comment by team172011** [comment]
Sorry, I accidentialy closed

**Comment by izeye** [comment]
@team172011 Ok, thanks for the quick answer!

**Pull request merged**
